language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 6.0.202
branches:
  only:
    - main
#    - develop
script:
  - dotnet build
  - dotnet test
# [START travis_deploy]
deploy:
    provider: gae
    # Skip cleanup so api_key.py and vendored dependencies are still there
    skip_cleanup: true
    keyfile: traviscisep22-e1dd1132cd0c.json
    project: traviscisep22
    version: service-demo
    default: true
    on:
        all_branches: true
# [END travis_deploy]